version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Maintain dependencies for Maven
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly